# Generated by Django 5.2.7 on 2025-10-29 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_herobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Если указать товар — баннер будет вести на его страницу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='store.product'),
        ),
    ]
