# Generated by Django 5.2.7 on 2025-10-29 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_herobanner_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobanner',
            name='product',
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='sales/', verbose_name='Баннер акции')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Скидка (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('related_products', models.ManyToManyField(blank=True, related_name='sales', to='store.product', verbose_name='Товары по акции')),
            ],
        ),
        migrations.AddField(
            model_name='herobanner',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='store.sale'),
        ),
    ]
