# Generated by Django 5.2.7 on 2025-10-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_herobanner_product_alter_herobanner_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='active',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='related_products',
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(related_name='sales', to='store.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sales/', verbose_name='Изображение баннера'),
        ),
    ]
