# Generated by Django 5.2.7 on 2025-10-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderitem_discount_percent_orderitem_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
